version: '3.7'

volumes:
  data_abm:

services:

  ide:
    image: kthb/kontarion:latest
    ports:
      - 8787:8787
    env_file: .Renviron
    environment: 
      - ROOT=true
      - USER=rstudio
      - PASSWORD=kontarion
    volumes:
      - data_abm:/root/.config/bibmon
      - .Renviron:/home/rstudio/.Renviron:ro
      - ./login.html:/etc/rstudio/login.html:ro
      - ./rserver.conf:/etc/rstudio/rserver.conf
      - ./home:/home/rstudio/home
      - ${HOME}/.config/bibmon:/home/rstudio/.config/bibmon
    command: /init 

  api:
    image: kthb/kontarion:latest
    ports:
      - 8080:8080
    env_file: .Renviron
    command: R -e "bibliomatrix::run_api(port = 8080, host = '0.0.0.0')" 
    working_dir: /usr/local/lib/R/site-library/bibliomatrix/plumber/abm
    volumes:
      - .Renviron:/root/.Renviron:ro
      - ${HOME}/.config/bibmon:/root/.config/bibmon

  app:
    image: kthb/kontarion:latest
    ports:
      - 8000:8000
    environment:
      - ABM_API=http://api:8080
    env_file: .Renviron
    command: R -e "bibliomatrix::run_app('abm', port = 8000, host = '0.0.0.0')"
    depends_on:
      - api
    volumes:
      - ${HOME}/.config/bibmon:/root/.config/bibmon


