library(hexSticker)
library(here)
library(magick)

# kontarion hexsticker

imgurl_src <- "logo-400.png"
imgurl_dest <- file.path(here(), "kontarion.png")

sticker(
  filename = imgurl_dest, 
      h_fill = "#e0e2e5", 
      h_color = RColorBrewer::brewer.pal(7, "Greys")[5],
      subplot = imgurl_src, s_x = 1, s_y = 1, s_width = 0.9,
      package = "", p_color = "#3e7131",
#      p_size = 20, s_x = 1, s_y = .75, s_width = .6
)

# dest location inspired by https://stackoverflow.com/questions/44113759
image_read(imgurl_dest) %>%
  image_resize("120x120") %>%
  image_write(imgurl_dest)

# KTH login screen logo

#imgurl_src <- "https://kth-library.github.io/assets/img/logo.png"

# the kth-logo-cirle is generated by this command 
# (requires imagemagick ie sudo apt install imagemagick-6.q16)
# convert -size 1186x1186 xc:none -fill kth-logo.png -draw "translate 593,593 circle 0,0 593,0" kth-logo-circle.png

 "https://www.kth.se/polopoly_fs/1.77257.1550147376!/KTH_Logotyp_RGB_2013-2.svg" %>%
 image_read_svg(width = 480, height = 480) %>%
 image_convert(format = "png") %>%
 image_resize("240x240") %>%
 image_write(path = "kth-logo.png")
