FROM ghcr.io/kth-library/skouton:latest

USER root

# add GITHUB_PAT due to rate limiting kicking in when installing packages
ARG GITHUB_PAT= 
ENV GITHUB_PAT=$GITHUB_PAT

# overwrite shiny server default app installation
COPY scripts/install_bibcap.sh /rocker_scripts/install_bibcap.sh
RUN /rocker_scripts/install_bibcap.sh

# avoid cache hit if none of the above scripts have been altered
COPY scripts /rocker_scripts

CMD /usr/bin/shiny-server.sh
